name: Dostukcha
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.12+12

environment:
  sdk: ">=3.0.0 <3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.3
  dartz: 0.10.1
  json_annotation: ^4.8.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  flutter_svg: ^2.0.6
  flutter_native_splash: ^2.3.0
  retrofit: ^4.0.1
  dio: ^5.1.2
  pretty_dio_logger: ^1.3.1
  permission_handler: ^10.4.3
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.0.15
  camera: ^0.10.5+7
  mask_text_input_formatter: ^2.4.0
  pinput: ^2.2.31
  image: ^4.0.17
  modal_bottom_sheet: ^2.1.2
  syncfusion_flutter_sliders: ^26.1.40
  lottie: ^2.3.2
  google_maps_flutter: ^2.2.8
  cached_network_image: ^3.2.3
  dropdown_button2: ^2.1.3
  go_router: ^7.1.1
  device_info_plus: ^8.0.0
  webview_flutter: ^4.2.2
  crypto: ^3.0.3
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.1.14
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  package_info_plus: ^4.2.0

dev_dependencies:
  injectable_generator: ^2.4.1
  retrofit_generator: ^7.0.1
  json_serializable:
  build_runner: ^2.4.6
  flutter_bugfender: ^2.1.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/anim/
    - config/
